version: "3.11"
services:
  web:
    restart: always
    build:
      context: ./.
      dockerfile: ./docker/Dockerfile
    command: uvicorn main:main --reload --host 0.0.0.0 --port 8000
    environment:
      APP_ENV: prod
    ports:
      - 8001:8000
    volumes:
      - ./media:/code/media
    networks:
      - default
      - service-common_default
networks:
  service-common_default:
    external: true
  default:
    driver: bridge
